service: aws-lambda-java-serverless-api

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: build/distributions/aws-lambda-java-serverless-api.zip

functions:
  currentTime:
    handler: api.Handler
    events:
      - http:
          path: ping
          method: get
